altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  1a4d4b5e-8e4a-4fe5-9f94-39b30c3051dd:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: ecc7124e-3906-49a5-ac59-5b18d2ff0613
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c59e7b1e-5d2c-4f1c-b290-984b8e105c2d
        userCondition: null
fs: drinks
handle: drinks
name: Drinks
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
