altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  e968f503-5d29-4bca-a38e-93da8c271ee1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 97a7a992-d849-4b8e-972a-4cb4e0dd2f04
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3b9e6db8-8b89-4a73-99e5-8477c86da152
        userCondition: null
fs: users
handle: users
name: Users
sortOrder: 2
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
