dateModified: 1721551878
email:
  fromEmail: admin@gmail.com
  fromName: 'Craft Coffee'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    85b21d30-6cb8-475c-8702-e68195f053c9: 'Craft Coffee' # Craft Coffee
    e1d43670-b30f-4045-9907-51f4ef317da4: 'Craft Coffee' # Craft Coffee
    f833cb99-d2a1-4338-a189-5dfd5782d9bf: 'Public Schema' # Public Schema
system:
  edition: solo
  live: true
  name: 'Craft Coffee'
  retryDuration: null
  schemaVersion: 5.0.0.21
  timeZone: Asia/Jakarta
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
