defaultPlacement: end
enableVersioning: true
entryTypes:
  - b1573dde-cf1e-418a-b204-b593ac89bb93 # Drinks
handle: drinks
maxAuthors: 1
name: Drinks
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  e1d43670-b30f-4045-9907-51f4ef317da4: # Craft Coffee
    enabledByDefault: true
    hasUrls: true
    template: drinks/_entry
    uriFormat: 'drinks/{slug}'
type: channel
