defaultPlacement: end
enableVersioning: true
entryTypes:
  - 041823ef-4ee0-442c-a620-f904fc14b84d # News
handle: news
maxAuthors: 1
name: News
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  e1d43670-b30f-4045-9907-51f4ef317da4: # Craft Coffee
    enabledByDefault: true
    hasUrls: true
    template: news/_entry
    uriFormat: 'news/{slug}'
type: channel
